# Generated by Django 5.0.6 on 2024-05-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapp1', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Customuser',
        ),
    ]
